#!/usr/bin/env python
# -*- mode:python; tab-width:4; c-basic-offset:4; intent-tabs-mode:nil; coding:utf-8 -*-
# ex: filetype=python tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent

#
# Universal Password Changer (UPwdChg)
# Copyright (C) 2014 Cedric Dufour <http://cedric.dufour.name>
# Author: Cedric Dufour <http://cedric.dufour.name>
#
# The Universal Password Changer (UPwdChg) is free software:
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, Version 3.
#
# The Universal Password Changer (UPwdChg) is distributed in the hope
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#

# Modules
# ... deb: python-ldap
from UPwdChg import TokenPlugin
import base64 as B64
import ldap

# Parameters
UPWDCHG_PLUGIN_CRITICAL=True
UPWDCHG_PLUGIN_DRYRUN=True
UPWDCHG_PLUGIN_AD_URI='ldap://ad.example.org:389'
UPWDCHG_PLUGIN_AD_ADMIN_DN='Administrator@AD.EXAMPLE.ORG'  # set to None to bind as user
UPWDCHG_PLUGIN_AD_ADMIN_PWD=''  # prefix with 'file://' to get password from specified file
UPWDCHG_PLUGIN_AD_USER_DN=None  # set to None to perform DN search
UPWDCHG_PLUGIN_AD_USER_SEARCH_DN='cn=Users,dc=ad,dc=example,dc=org'
UPWDCHG_PLUGIN_AD_USER_SEARCH_SCOPE=ldap.SCOPE_ONELEVEL
UPWDCHG_PLUGIN_AD_USER_SEARCH_FILTER='uid=%{USERNAME}'

# Plugin
class ChangePasswordAd(TokenPlugin):

    def __init__( self ):
        global UPWDCHG_PLUGIN_CRITICAL
        TokenPlugin.__init__( self, 'ChangePasswordAd', UPWDCHG_PLUGIN_CRITICAL )

    def process( self ):
        global \
            UPWDCHG_PLUGIN_DRYRUN, \
            UPWDCHG_PLUGIN_AD_URI, \
            UPWDCHG_PLUGIN_AD_ADMIN_DN, \
            UPWDCHG_PLUGIN_AD_ADMIN_PWD, \
            UPWDCHG_PLUGIN_AD_USER_DN, \
            UPWDCHG_PLUGIN_AD_USER_SEARCH_DN, \
            UPWDCHG_PLUGIN_AD_USER_SEARCH_SCOPE, \
            UPWDCHG_PLUGIN_AD_USER_SEARCH_FILTER

        # Get token (data)
        dToken = self._getToken()
        sUsername = dToken['username'].encode( 'utf-8' )
        sPasswordOld = dToken['password-old'].encode( 'utf-8' )
        sPasswordNew = dToken['password-new'].encode( 'utf-8' )

        # Process token data

        # ... Active Directory bind credentials
        if UPWDCHG_PLUGIN_AD_ADMIN_DN is not None:
            sBindDn = UPWDCHG_PLUGIN_AD_ADMIN_DN
            if UPWDCHG_PLUGIN_AD_ADMIN_PWD is None:
                sBindPwd=''  # Really!?!
            elif UPWDCHG_PLUGIN_AD_ADMIN_PWD.startswith( 'file://' ):
                __sFile = UPWDCHG_PLUGIN_AD_ADMIN_PWD[7:]
                try:
                    __oFile = open( __sFile, 'r' )
                    sBindPwd = __oFile.readline()
                    __oFile.close()
                except Exception as e:
                    self._DEBUG( 'Failed to retrieve Active Directory bind password from file; %s' % str( e ) )
                    self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
            else:
                sBindPwd = UPWDCHG_PLUGIN_AD_ADMIN_PWD
        else:
            if UPWDCHG_PLUGIN_AD_USER_DN is None:
                self._DEBUG( 'Missing user distinguished name (DN)' )
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
            sBindDn = UPWDCHG_PLUGIN_AD_USER_DN.replace( '%{USERNAME}', sUsername )
            sBindPwd = sPasswordOld

        # ... Active Directory bind
        try:
            oLdap = ldap.initialize( UPWDCHG_PLUGIN_AD_URI )
            oLdap.protocol_version = ldap.VERSION3
            oLdap.bind_s( sBindDn, sBindPwd, ldap.AUTH_SIMPLE )
        except Exception as e:
            self._DEBUG( 'Failed to bind to Active Directory server; %s' % str( e ) )
            if UPWDCHG_PLUGIN_AD_ADMIN_DN is not None:
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
            else:
                self._EXIT_ERROR( 'Invalid Active Directory credentials' )

        # ... Active directory user DN
        if UPWDCHG_PLUGIN_AD_USER_DN is None:
            try:
                lLdapResults = oLdap.search_ext_s(
                    UPWDCHG_PLUGIN_AD_USER_SEARCH_DN,
                    UPWDCHG_PLUGIN_AD_USER_SEARCH_SCOPE,
                    UPWDCHG_PLUGIN_AD_USER_SEARCH_FILTER.replace( '%{USERNAME}', sUsername ),
                    attrlist=[ 'dn' ], attrsonly=1, sizelimit=2
                    )
                if not lLdapResults:
                    raise Exception( 'user not found' )
                elif len( lLdapResults ) > 1:
                    raise Exception( 'too many match' )
            except Exception as e:
                self._DEBUG( 'Failed to perform Active Directory user DN search; %s' % str( e ) )
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
            ( sUserDn, dAttrs ) = lLdapResults[0]
        else:
            sUserDn = UPWDCHG_PLUGIN_AD_USER_DN.replace( '%{USERNAME}', sUsername )

        # ... Active Directory password change
        #     REF: http://support.microsoft.com/kb/263991
        if not UPWDCHG_PLUGIN_DRYRUN:
            try:
                if UPWDCHG_PLUGIN_AD_ADMIN_DN is not None:
                    lLDIF = [
                        ( ldap.MOD_REPLACE, 'unicodePwd', ( '"%s"' % dToken['password-new'] ).encode( 'utf-16-le' ) ),
                    ]
                else:
                    lLDIF = [
                        ( ldap.MOD_DELETE, 'unicodePwd', ( '"%s"' % dToken['password-old'] ).encode( 'utf-16-le' ) ),
                        ( ldap.MOD_ADD, 'unicodePwd', ( '"%s"' % dToken['password-new'] ).encode( 'utf-16-le' ) ),
                    ]
                oLdap.modify_s( sUserDn, lLDIF )
            except Exception as e:
                self._DEBUG( 'Failed to change Active Directory password; %s' % str( e ) )
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )

        # ... Active Directory unbind
        try:
            oLdap.unbind_s()
        except Exception as e:
            self._DEBUG( 'Failed to unbind from Active Directory server; %s' % str( e ) )

        # Done
        self._EXIT_OK( 'Active Directory password successfully changed' )

# Process
ChangePasswordAd().process()

