#!/usr/bin/env python
# -*- mode:python; tab-width:4; c-basic-offset:4; intent-tabs-mode:nil; -*-
# ex: filetype=python tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent

#
# Universal Password Changer (UPwdChg)
# Copyright (C) 2014-2018 Cedric Dufour <http://cedric.dufour.name>
# Author: Cedric Dufour <http://cedric.dufour.name>
#
# The Universal Password Changer (UPwdChg) is free software:
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, Version 3.
#
# The Universal Password Changer (UPwdChg) is distributed in the hope
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#
# SPDX-License-Identifier: GPL-3.0
# License-Filename: LICENSE/GPL-3.0.txt
#

# Modules
from UPwdChg import TokenPlugin
import subprocess as SP

# Parameters
UPWDCHG_PLUGIN_CRITICAL=True
UPWDCHG_PLUGIN_DEBUG=TokenPlugin.DEBUG_INFO
UPWDCHG_PLUGIN_DRYRUN=True

# ... Kerberos 5
UPWDCHG_PLUGIN_KRB5_PRINCIPAL='%{USERNAME}@EXAMPLE.ORG'
UPWDCHG_PLUGIN_KRB5_ADMSRV='root@krb5adm.example.org'  # if not None, SSH to specified server to execute 'kadmin.local' actions

# Plugin
class ChangePasswordKrb5(TokenPlugin):

    def __init__(self):
        global UPWDCHG_PLUGIN_CRITICAL, UPWDCHG_PLUGIN_DEBUG
        TokenPlugin.__init__(self, 'ChangePasswordKrb5', UPWDCHG_PLUGIN_CRITICAL, UPWDCHG_PLUGIN_DEBUG)

    def __escapeLocal(self, _s):
        return _s.replace('"', '""')

    def __escapeSsh(self, _s):
        return _s.replace('"', '""').replace('\'', '\'"\'"\'')

    def process(self):
        global \
            UPWDCHG_PLUGIN_DRYRUN, \
            UPWDCHG_PLUGIN_KRB5_PRINCIPAL, \
            UPWDCHG_PLUGIN_KRB5_ADMSRV

        # Check parameters
        if not UPWDCHG_PLUGIN_KRB5_PRINCIPAL:
            self._DEBUG('Missing principal')
            self._EXIT_ERROR('Internal error; please contact your system administrator')
        if UPWDCHG_PLUGIN_KRB5_ADMSRV is not None and not UPWDCHG_PLUGIN_KRB5_ADMSRV:
            self._DEBUG('Empty administration server connection string')
            self._EXIT_ERROR('Internal error; please contact your system administrator')

        # Get token (data)
        oToken = self._getToken()
        sUsername = oToken['username'].encode('utf-8')
        sPasswordNew = oToken['password-new'].encode('utf-8')

        # Change Kerberos password

        # ... principal
        sPrincipal = UPWDCHG_PLUGIN_KRB5_PRINCIPAL.replace('%{USERNAME}', sUsername)

        # ... password change
        try:
            if not UPWDCHG_PLUGIN_DRYRUN:
                if UPWDCHG_PLUGIN_KRB5_ADMSRV is None:
                    lCommand = [ 'kadmin.local', '-q', "'change_password -pw \"%s\" \"%s\"'" % (self.__escapeLocal(sPasswordNew), self.__escapeLocal(sPrincipal)) ]
                else:
                    # WARNING: remote command is executed by OpenSSH via the (remote) user's shell!
                    lCommand = [ 'ssh', '-x', UPWDCHG_PLUGIN_KRB5_ADMSRV, '--', 'kadmin.local', '-q', "'change_password -pw \"%s\" \"%s\"'" % (self.__escapeSsh(sPasswordNew), self.__escapeSsh(sPrincipal)) ]
                oPopen = SP.Popen(lCommand, stdout=SP.PIPE, stderr=SP.PIPE)
                (sStdOut, sStdErr) = oPopen.communicate()
                if oPopen.returncode != 0 or sStdErr:
                    raise Exception(sStdErr)
                self._DEBUG('Successfully changed password for principal: %s' % sPrincipal, TokenPlugin.DEBUG_INFO)
            else:
                self._DEBUG('DRY-RUN! NOT changing password for principal: %s' % sPrincipal, TokenPlugin.DEBUG_WARNING)
        except Exception as e:
            self._DEBUG('Failed to change password; %s' % str(e))
            self._EXIT_ERROR('Internal error; please contact your system administrator')

        # Done
        self._EXIT_OK('Password successfully changed')

# Process
ChangePasswordKrb5().process()
