#!/usr/bin/env python
# -*- mode:python; tab-width:4; c-basic-offset:4; intent-tabs-mode:nil; -*-
# ex: filetype=python tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent

#
# Universal Password Changer (UPwdChg)
# Copyright (C) 2014 Cedric Dufour <http://cedric.dufour.name>
# Author: Cedric Dufour <http://cedric.dufour.name>
#
# The Universal Password Changer (UPwdChg) is free software:
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, Version 3.
#
# The Universal Password Changer (UPwdChg) is distributed in the hope
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#

# Modules
from UPwdChg import TokenPlugin
import subprocess as SP

# Parameters
UPWDCHG_PLUGIN_CRITICAL=True
UPWDCHG_PLUGIN_DRYRUN=True
UPWDCHG_PLUGIN_DEBUG=TokenPlugin.DEBUG_INFO

# ... Kerberos 5
UPWDCHG_PLUGIN_KRB5_PRINCIPAL='%{USERNAME}@EXAMPLE.ORG'
UPWDCHG_PLUGIN_KRB5_ADMSRV='root@krb5adm.example.org'  # if not None, SSH to specified server to execute 'kadmin.local' actions

# Plugin
class ChangePasswordKrb5(TokenPlugin):

    def __init__( self ):
        global UPWDCHG_PLUGIN_CRITICAL
        TokenPlugin.__init__( self, 'ChangePasswordKrb5', UPWDCHG_PLUGIN_CRITICAL, UPWDCHG_PLUGIN_DEBUG )

    def process( self ):
        global \
            UPWDCHG_PLUGIN_DRYRUN, \
            UPWDCHG_PLUGIN_KRB5_PRINCIPAL, \
            UPWDCHG_PLUGIN_KRB5_ADMSRV

        # Check parameters
        if not UPWDCHG_PLUGIN_KRB5_PRINCIPAL:
            self._DEBUG( 'Missing principal' )
            self._EXIT_ERROR( 'Internal error; please contact your system administrator' )

        # Get token (data)
        dToken = self._getToken()
        sUsername = dToken['username'].encode( 'utf-8' )
        sPasswordNew = dToken['password-new'].encode( 'utf-8' )

        # Process token data

        # ... principal
        sPrincipal = UPWDCHG_PLUGIN_KRB5_PRINCIPAL.replace( '%{USERNAME}', sUsername )

        # ... password change
        if not UPWDCHG_PLUGIN_DRYRUN:
            try:
                lCommand = [ 'kadmin.local', '-q', "'change_password -pw \"%s\" \"%s\"'" % ( sPasswordNew.replace('"', '""'), sPrincipal.replace('"', '""') ) ]
                if UPWDCHG_PLUGIN_KRB5_ADMSRV:
                    lCommand = [ 'ssh', '-x', UPWDCHG_PLUGIN_KRB5_ADMSRV, '--', ' '.join( lCommand ) ]
                oPopen = SP.Popen( lCommand, stdout=SP.PIPE, stderr=SP.PIPE )
                ( sStdOut, sStdErr ) = oPopen.communicate()
                if oPopen.returncode != 0 or sStdErr:
                    raise Exception( sStdErr )
            except Exception as e:
                self._DEBUG( 'Failed to change password; %s' % str( e ) )
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
            self._DEBUG( 'Successfully changed password for principal: %s' % sPrincipal, TokenPlugin.DEBUG_INFO )

        # Done
        self._EXIT_OK( 'Password successfully changed' )

# Process
ChangePasswordKrb5().process()
