#!/usr/bin/env python
# -*- mode:python; tab-width:4; c-basic-offset:4; intent-tabs-mode:nil; -*-
# ex: filetype=python tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent

#
# Universal Password Changer (UPwdChg)
# Copyright (C) 2014-2018 Cedric Dufour <http://cedric.dufour.name>
# Author: Cedric Dufour <http://cedric.dufour.name>
#
# The Universal Password Changer (UPwdChg) is free software:
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, Version 3.
#
# The Universal Password Changer (UPwdChg) is distributed in the hope
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#
# SPDX-License-Identifier: GPL-3.0
# License-Filename: LICENSE/GPL-3.0.txt
#

# Modules
from UPwdChg import TokenPlugin
import string

# Parameters
UPWDCHG_PLUGIN_CRITICAL=True
UPWDCHG_PLUGIN_DEBUG=TokenPlugin.DEBUG_INFO

# ... length; int: 0/None=ignore
UPWDCHG_PLUGIN_PASSWORD_LENGTH_MINIMUM=8
UPWDCHG_PLUGIN_PASSWORD_LENGTH_MAXIMUM=64
# ... forbidden characters
UPWDCHG_PLUGIN_PASSWORD_CHARSET_FORBIDDEN=''
# ... forbidden/required character types; int: -1=forbidden, 1=required, 0/None=ignore
UPWDCHG_PLUGIN_PASSWORD_CHARSET_NOTASCII=-1
UPWDCHG_PLUGIN_PASSWORD_TYPE_LOWER=0
UPWDCHG_PLUGIN_PASSWORD_TYPE_UPPER=0
UPWDCHG_PLUGIN_PASSWORD_TYPE_DIGIT=0
UPWDCHG_PLUGIN_PASSWORD_TYPE_PUNCT=0
UPWDCHG_PLUGIN_PASSWORD_TYPE_OTHER=0
# ... types quantity; int: 0/None=ignore
UPWDCHG_PLUGIN_PASSWORD_TYPE_MINIMUM=0

# Plugin
class CheckPasswordPolicy(TokenPlugin):

    def __init__(self):
        global UPWDCHG_PLUGIN_CRITICAL, UPWDCHG_PLUGIN_DEBUG
        TokenPlugin.__init__(self, 'CheckPasswordPolicy', UPWDCHG_PLUGIN_CRITICAL, UPWDCHG_PLUGIN_DEBUG)

    def process(self):
        global \
            UPWDCHG_PLUGIN_PASSWORD_LENGTH_MINIMUM, \
            UPWDCHG_PLUGIN_PASSWORD_LENGTH_MAXIMUM, \
            UPWDCHG_PLUGIN_PASSWORD_CHARSET_FORBIDDEN, \
            UPWDCHG_PLUGIN_PASSWORD_CHARSET_NOTASCII, \
            UPWDCHG_PLUGIN_PASSWORD_TYPE_LOWER, \
            UPWDCHG_PLUGIN_PASSWORD_TYPE_UPPER, \
            UPWDCHG_PLUGIN_PASSWORD_TYPE_DIGIT, \
            UPWDCHG_PLUGIN_PASSWORD_TYPE_PUNCT, \
            UPWDCHG_PLUGIN_PASSWORD_TYPE_OTHER, \
            UPWDCHG_PLUGIN_PASSWORD_TYPE_MINIMUM

        # Get token (data)
        oToken = self._getToken()
        uPasswordNew = oToken['password-new']
        sPasswordNew = uPasswordNew.encode('utf-8')

        # Check the password policy
        bError = False
        lsOutputs = list()

        # ... check password length
        if UPWDCHG_PLUGIN_PASSWORD_LENGTH_MINIMUM and len(uPasswordNew) < UPWDCHG_PLUGIN_PASSWORD_LENGTH_MINIMUM:
            lsOutputs.append('Password MUST contain at least %d characters' % UPWDCHG_PLUGIN_PASSWORD_LENGTH_MINIMUM)
            bError = True
        if UPWDCHG_PLUGIN_PASSWORD_LENGTH_MAXIMUM and len(uPasswordNew) > UPWDCHG_PLUGIN_PASSWORD_LENGTH_MAXIMUM:
            lsOutputs.append('Password may NOT contain more than %d characters' % UPWDCHG_PLUGIN_PASSWORD_LENGTH_MAXIMUM)
            bError = True

        # ... check character classes
        bForbidden = False
        bNotAscii = False
        bLower = False
        bUpper = False
        bDigit = False
        bPunct = False
        bOther = False
        iType = 0
        for sCharacter in sPasswordNew:
            if sCharacter in UPWDCHG_PLUGIN_PASSWORD_CHARSET_FORBIDDEN:
                bForbidden = True
            if ord(sCharacter) < 32 or ord(sCharacter) > 126:
                bNotAscii = True
            if sCharacter in string.lowercase:
                if not bLower:
                    bLower = True
                    iType += 1
            elif sCharacter in string.uppercase:
                if not bUpper:
                    bUpper = True
                    iType += 1
            elif sCharacter in string.digits:
                if not bDigit:
                    bDigit = True
                    iType += 1
            elif sCharacter in string.punctuation:
                if not bPunct:
                    bPunct = True
                    iType += 1
            else:
                if not bOther:
                    bOther = True
                    iType += 1
        if bForbidden:
            lsOutputs.append('Password may NOT contain any forbidden character')
            bError = True
        if UPWDCHG_PLUGIN_PASSWORD_CHARSET_NOTASCII:
            if bNotAscii and UPWDCHG_PLUGIN_PASSWORD_CHARSET_NOTASCII<0:
                lsOutputs.append('Password may NOT contain any non-ASCII character')
                bError = True
            elif not bNotAscii and UPWDCHG_PLUGIN_PASSWORD_CHARSET_NOTASCII>0:
                lsOutputs.append('Password MUST contain at least one non-ASCII character')
                bError = True
        if UPWDCHG_PLUGIN_PASSWORD_TYPE_LOWER:
            if bLower and UPWDCHG_PLUGIN_PASSWORD_TYPE_LOWER<0:
                lsOutputs.append('Password may NOT contain any lowercase character')
                bError = True
            elif not bLower and UPWDCHG_PLUGIN_PASSWORD_TYPE_LOWER>0:
                lsOutputs.append('Password MUST contain at least one lowercase character')
                bError = True
        if UPWDCHG_PLUGIN_PASSWORD_TYPE_UPPER:
            if bUpper and UPWDCHG_PLUGIN_PASSWORD_TYPE_UPPER<0:
                lsOutputs.append('Password may NOT contain any uppercase character')
                bError = True
            elif not bUpper and UPWDCHG_PLUGIN_PASSWORD_TYPE_UPPER>0:
                lsOutputs.append('Password MUST contain at least one uppercase character')
                bError = True
        if UPWDCHG_PLUGIN_PASSWORD_TYPE_DIGIT:
            if bDigit and UPWDCHG_PLUGIN_PASSWORD_TYPE_DIGIT<0:
                lsOutputs.append('Password may NOT contain any digit')
                bError = True
            elif not bDigit and UPWDCHG_PLUGIN_PASSWORD_TYPE_DIGIT>0:
                lsOutputs.append('Password MUST contain at least one digit')
                bError = True
        if UPWDCHG_PLUGIN_PASSWORD_TYPE_PUNCT:
            if bPunct and UPWDCHG_PLUGIN_PASSWORD_TYPE_PUNCT<0:
                lsOutputs.append('Password may NOT contain any punctuation mark')
                bError = True
            elif not bPunct and UPWDCHG_PLUGIN_PASSWORD_TYPE_PUNCT>0:
                lsOutputs.append('Password MUST contain at least one punctuation mark')
                bError = True
        if UPWDCHG_PLUGIN_PASSWORD_TYPE_OTHER:
            if bOther and UPWDCHG_PLUGIN_PASSWORD_TYPE_OTHER<0:
                lsOutputs.append('Password may NOT contain any special character')
                bError = True
            elif not bOther and UPWDCHG_PLUGIN_PASSWORD_TYPE_OTHER>0:
                lsOutputs.append('Password MUST contain at least one special character')
                bError = True
        if UPWDCHG_PLUGIN_PASSWORD_TYPE_MINIMUM and iType < UPWDCHG_PLUGIN_PASSWORD_TYPE_MINIMUM:
            lsOutputs.append('Password MUST contain at least %d different character types' % UPWDCHG_PLUGIN_PASSWORD_TYPE_MINIMUM)
            bError = True

        # Done
        if bError:
            self._EXIT_ERROR(lsOutputs)
        self._DEBUG('Password matches policy', TokenPlugin.DEBUG_NOTICE)
        self._EXIT_OK('Password matches policy requirements')

# Process
CheckPasswordPolicy().process()
