#!/usr/bin/env python
# -*- mode:python; tab-width:4; c-basic-offset:4; intent-tabs-mode:nil; -*-
# ex: filetype=python tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent

#
# Universal Password Changer (UPwdChg)
# Copyright (C) 2014 Cedric Dufour <http://cedric.dufour.name>
# Author: Cedric Dufour <http://cedric.dufour.name>
#
# The Universal Password Changer (UPwdChg) is free software:
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, Version 3.
#
# The Universal Password Changer (UPwdChg) is distributed in the hope
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#

# Modules
from UPwdChg import \
     UPWDCHG_DEFAULT_DIR_PUBLIC, \
     TokenPlugin
import os
import sys

# Parameters
UPWDCHG_PLUGIN_CRITICAL=True
UPWDCHG_PLUGIN_DEBUG=TokenPlugin.DEBUG_INFO

# ... Password nonce
UPWDCHG_PLUGIN_PASSWORD_NONCE_DIR=UPWDCHG_DEFAULT_DIR_PUBLIC

# Plugin
class CheckPasswordNonce(TokenPlugin):

    def __init__(self):
        global UPWDCHG_PLUGIN_CRITICAL, UPWDCHG_PLUGIN_DEBUG
        TokenPlugin.__init__(self, 'CheckPasswordNonce', UPWDCHG_PLUGIN_CRITICAL, UPWDCHG_PLUGIN_DEBUG)

    def process(self):
        global UPWDCHG_PLUGIN_PASSWORD_NONCE_DIR

        # Get token (data)
        oToken = self._getToken()
        uUsername = oToken['username']
        if 'password-nonce' not in oToken.keys():
            self._DEBUG('Token has no "password-nonce" attribute')
            self._EXIT_ERROR('Internal error; please contact your system administrator')
        uPasswordNonce = oToken['password-nonce']
        (uPasswordNonce_id, uPasswordNonce_secret) = oToken.splitPasswordNonce(uPasswordNonce)
        if 'session-id' in oToken.keys():
            uSessionId = oToken['session-id']
        else:
            uSessionId = None

        # Check corresponding "password-nonce" token
        try:
            # ... read token
            oToken_nonce = self._getTokenReader()
            sFileToken_nonce = UPWDCHG_PLUGIN_PASSWORD_NONCE_DIR.rstrip(os.sep)+os.sep+uPasswordNonce_id.encode(sys.getfilesystemencoding())+'.nonce'
            if oToken_nonce.readToken(sFileToken_nonce):
                self._DEBUG('Invalid "password-nonce" ID/file; %s' % sFileToken_nonce)
                self._EXIT_ERROR('Invalid password nonce (PIN code)')

            # ... check password nonce
            iReturn = oToken_nonce.checkData_PasswordNonce(uUsername, uPasswordNonce, uSessionId)
            if iReturn:
                if iReturn == 1:
                    self._DEBUG('"password-nonce" token has expired; %s' % sFileToken_nonce)
                    self._EXIT_ERROR('Password nonce (PIN code) has expired; %s-...' % uPasswordNonce_id)
                elif iReturn == 2:
                    self._DEBUG('Invalid "password-nonce" secret; %s' % sFileToken_nonce)
                    self._EXIT_ERROR('Invalid password nonce (PIN code)')
                elif iReturn == 3:
                    self._DEBUG('Invalid session; %s' % sFileToken_nonce)
                    self._EXIT_ERROR('Invalid session. Please start over.')
                self._DEBUG('Invalid "password-nonce" check return code; %d' % iReturn)
                self._EXIT_ERROR('Internal error; please contact your system administrator')
            self._DEBUG('Valid password nonce', TokenPlugin.DEBUG_NOTICE)
        except Exception as e:
            self._DEBUG('Failed to check password nonce; %s' % str(e))
            self._EXIT_ERROR('Internal error; please contact your system administrator')

        # Done
        self._EXIT_OK('Valid password nonce (PIN code)')

# Process
CheckPasswordNonce().process()
