#!/usr/bin/env python
# -*- mode:python; tab-width:4; c-basic-offset:4; intent-tabs-mode:nil; -*-
# ex: filetype=python tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent

#
# Universal Password Changer (UPwdChg)
# Copyright (C) 2014 Cedric Dufour <http://cedric.dufour.name>
# Author: Cedric Dufour <http://cedric.dufour.name>
#
# The Universal Password Changer (UPwdChg) is free software:
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, Version 3.
#
# The Universal Password Changer (UPwdChg) is distributed in the hope
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#

# Modules
from UPwdChg import TokenPlugin

# Parameters
UPWDCHG_PLUGIN_CRITICAL=True

# Plugin
class CheckActualChange(TokenPlugin):

    def __init__(self):
        global UPWDCHG_PLUGIN_CRITICAL
        TokenPlugin.__init__(self, 'CheckActualChange', UPWDCHG_PLUGIN_CRITICAL)

    def process(self):
        # Get token (data)
        dToken = self._getToken()

        # Process token data
        # ... check actual password change
        if dToken['password-new'] == dToken['password-old']:
            self._EXIT_ERROR('New password must be different from old password')

        # Done
        self._EXIT_OK('Actual password change')

# Process
CheckActualChange().process()

