#!/usr/bin/env python3
# -*- mode:python; tab-width:4; c-basic-offset:4; intent-tabs-mode:nil; -*-
# ex: filetype=python tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent

#
# Universal Password Changer (UPwdChg)
# Copyright (C) 2014-2018 Cedric Dufour <http://cedric.dufour.name>
# Author: Cedric Dufour <http://cedric.dufour.name>
#
# The Universal Password Changer (UPwdChg) is free software:
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, Version 3.
#
# The Universal Password Changer (UPwdChg) is distributed in the hope
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#
# SPDX-License-Identifier: GPL-3.0
# License-Filename: LICENSE/GPL-3.0.txt
#

#------------------------------------------------------------------------------
# DEPENDENCIES
#------------------------------------------------------------------------------

# UPwdChg
from UPwdChg import TokenPlugin

# Standard
import subprocess as SP
import sys


#------------------------------------------------------------------------------
# CONFIGURATION
#------------------------------------------------------------------------------

# UPwdChg
UPWDCHG_PLUGIN_NAME='CreateAccountKrb5'
UPWDCHG_PLUGIN_CRITICAL=True
UPWDCHG_PLUGIN_DEBUG=TokenPlugin.DEBUG_INFO
UPWDCHG_PLUGIN_DRYRUN=True

# Kerberos 5
UPWDCHG_PLUGIN_KRB5_PRINCIPAL='%{USERNAME}@EXAMPLE.ORG'
UPWDCHG_PLUGIN_KRB5_ADD_USER_DN='uid=%{USERNAME},ou=users,dc=example,dc=org'
UPWDCHG_PLUGIN_KRB5_ADD_OPTIONS='-policy default'
UPWDCHG_PLUGIN_KRB5_ADMSRV='root@krb5adm.example.org'  # if not None, SSH to specified server to execute 'kadmin.local' actions


#------------------------------------------------------------------------------
# PLUGIN
#------------------------------------------------------------------------------

class CreateAccountKrb5(TokenPlugin):

    def __init__(self):
        TokenPlugin.__init__(self, UPWDCHG_PLUGIN_NAME, UPWDCHG_PLUGIN_CRITICAL, UPWDCHG_PLUGIN_DEBUG)


    def __escape(self, _s):
        return _s.replace('"', '""').replace('\'', '\'"\'"\'')


    def process(self):
        # Check configuration
        if not UPWDCHG_PLUGIN_KRB5_PRINCIPAL:
            self._DEBUG('Missing principal')
            self._EXIT_ERROR('Internal error; please contact your system administrator')
        if not UPWDCHG_PLUGIN_KRB5_ADD_USER_DN:
            self._DEBUG('Missing user distinguished name (DN)')
            self._EXIT_ERROR('Internal error; please contact your system administrator')
        if UPWDCHG_PLUGIN_KRB5_ADMSRV is not None and not UPWDCHG_PLUGIN_KRB5_ADMSRV:
            self._DEBUG('Empty administration server connection string')
            self._EXIT_ERROR('Internal error; please contact your system administrator')

        # Get token (data)
        oToken = self._getToken()
        sUsername = oToken['username']
        sPasswordNew = oToken['password-new']

        # Process token data

        # ... Kerberos principal
        sPrincipal = UPWDCHG_PLUGIN_KRB5_PRINCIPAL.replace('%{USERNAME}', sUsername)

        # ... Check principal existency
        bPrincipalExists = True
        try:
            lCommand = [ 'kadmin.local', '-q', "'get_principal -terse \"%s\"'" % self.__escape(sPrincipal) ]
            if UPWDCHG_PLUGIN_KRB5_ADMSRV is not None:
                lCommand_ssh = [ 'ssh', '-x', UPWDCHG_PLUGIN_KRB5_ADMSRV, '--' ]
                lCommand_ssh.extend(lCommand)
                lCommand = lCommand_ssh
            oPopen = SP.Popen(lCommand, stdout=SP.PIPE, stderr=SP.PIPE)
            (byStdOut, byStdErr) = oPopen.communicate()
            if oPopen.returncode != 0 or byStdErr:
                sStdErr = byStdErr.decode(sys.stderr.encoding)
                if sStdErr.lower().find('principal does not exist') < 0:
                    raise Exception(sStdErr)
                bPrincipalExists = False
            if bPrincipalExists:
                self._DEBUG('Principal already exists (its password will be updated): %s' % sPrincipal, TokenPlugin.DEBUG_NOTICE)
            else:
                self._DEBUG('Principal does not exists (and will be created): %s' % sPrincipal, TokenPlugin.DEBUG_NOTICE)
        except Exception as e:
            self._DEBUG('Failed to change password; %s' % str(e))
            self._EXIT_ERROR('Internal error; please contact your system administrator')

        # ... Kerberos password change (?)
        try:
            if bPrincipalExists:
                if not UPWDCHG_PLUGIN_DRYRUN:
                    lCommand = [ 'kadmin.local', '-q', "'change_password -pw \"%s\" \"%s\"'" % (self.__escape(sPasswordNew), self.__escape(sPrincipal)) ]
                    if UPWDCHG_PLUGIN_KRB5_ADMSRV is not None:
                        lCommand_ssh = [ 'ssh', '-x', UPWDCHG_PLUGIN_KRB5_ADMSRV, '--' ]
                        lCommand_ssh.extend(lCommand)
                        lCommand = lCommand_ssh
                    oPopen = SP.Popen(lCommand, stdout=SP.PIPE, stderr=SP.PIPE)
                    (byStdOut, byStdErr) = oPopen.communicate()
                    if oPopen.returncode != 0 or byStdErr:
                        raise Exception(byStdErr.decode(sys.stderr.encoding))
                    self._DEBUG('Successfully changed password for principal: %s' % sPrincipal, TokenPlugin.DEBUG_INFO)
                else:
                    self._DEBUG('DRY-RUN! NOT changing password for principal: %s' % sPrincipal, TokenPlugin.DEBUG_WARNING)
        except Exception as e:
            self._DEBUG('Failed to change password; %s' % str(e))
            self._EXIT_ERROR('Internal error; please contact your system administrator')

        # ... Create principal (?)
        try:
            if not bPrincipalExists:
                if not UPWDCHG_PLUGIN_DRYRUN:
                    sUserDn = UPWDCHG_PLUGIN_KRB5_ADD_USER_DN.replace('%{USERNAME}', sUsername)
                    self._DEBUG('Creating principal (DN): %s (%s)' % (sPrincipal, sUserDn), TokenPlugin.DEBUG_TRACE)
                    sOptions = UPWDCHG_PLUGIN_KRB5_ADD_OPTIONS
                    lCommand = [ 'kadmin.local', '-q', "'add_principal -x dn=\"%s\" -pw \"%s\" %s \"%s\"'" % (self.__escape(sUserDn), self.__escape(sPasswordNew), sOptions, self.__escape(sPrincipal)) ]
                    if UPWDCHG_PLUGIN_KRB5_ADMSRV is not None:
                        lCommand_ssh = [ 'ssh', '-x', UPWDCHG_PLUGIN_KRB5_ADMSRV, '--' ]
                        lCommand_ssh.extend(lCommand)
                        lCommand = lCommand_ssh
                    oPopen = SP.Popen(lCommand, stdout=SP.PIPE, stderr=SP.PIPE)
                    (byStdOut, byStdErr) = oPopen.communicate()
                    if oPopen.returncode != 0 or byStdErr:
                        raise Exception(byStdErr.decode(sys.stderr.encoding))
                    self._DEBUG('Successfully created principal: %s' % sPrincipal, TokenPlugin.DEBUG_INFO)
                else:
                    self._DEBUG('DRY-RUN! NOT creating principal: %s' % sPrincipal, TokenPlugin.DEBUG_WARNING)
        except Exception as e:
            self._DEBUG('Failed to create principal; %s' % str(e))
            self._EXIT_ERROR('Internal error; please contact your system administrator')

        # Done
        if bPrincipalExists:
            self._EXIT_OK('Password successfully changed')
        else:
            self._EXIT_OK('Account successfully created')


# Process
CreateAccountKrb5().process()
