#!/usr/bin/env python
# -*- mode:python; tab-width:4; c-basic-offset:4; intent-tabs-mode:nil; -*-
# ex: filetype=python tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent

#
# Universal Password Changer (UPwdChg)
# Copyright (C) 2014-2018 Cedric Dufour <http://cedric.dufour.name>
# Author: Cedric Dufour <http://cedric.dufour.name>
#
# The Universal Password Changer (UPwdChg) is free software:
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, Version 3.
#
# The Universal Password Changer (UPwdChg) is distributed in the hope
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#
# SPDX-License-Identifier: GPL-3.0
# License-Filename: LICENSE/GPL-3.0.txt
#

# Modules
from UPwdChg import \
     UPWDCHG_DEFAULT_DIR_PUBLIC, \
     TokenPlugin
import os
import sys

# Parameters
UPWDCHG_PLUGIN_CRITICAL=True
UPWDCHG_PLUGIN_DEBUG=TokenPlugin.DEBUG_INFO
UPWDCHG_PLUGIN_DRYRUN=False

# ... password nonce
UPWDCHG_PLUGIN_PASSWORD_NONCE_DIR=UPWDCHG_DEFAULT_DIR_PUBLIC

# Plugin
class NukePasswordNonce(TokenPlugin):

    def __init__(self):
        global UPWDCHG_PLUGIN_CRITICAL, UPWDCHG_PLUGIN_DEBUG
        TokenPlugin.__init__(self, 'NukePasswordNonce', UPWDCHG_PLUGIN_CRITICAL, UPWDCHG_PLUGIN_DEBUG)

    def process(self):
        global UPWDCHG_PLUGIN_DRYRUN, UPWDCHG_PLUGIN_PASSWORD_NONCE_DIR

        # Get token (data)
        oToken = self._getToken()
        uUsername = oToken['username']
        if 'password-nonce' not in oToken.getData().keys():
            self._DEBUG('Token contains no password nonce')
            self._EXIT_ERROR('Internal error; please contact your system administrator')
        uPasswordNonce = oToken['password-nonce']
        (uPasswordNonce_id, uPasswordNonce_secret) = oToken.splitPasswordNonce(uPasswordNonce)

        # Delete "password-nonce" token
        try:
            sFileToken_nonce = UPWDCHG_PLUGIN_PASSWORD_NONCE_DIR.rstrip(os.sep)+os.sep+uPasswordNonce_id.encode(sys.getfilesystemencoding())+'.nonce'
            if not UPWDCHG_PLUGIN_DRYRUN:
                os.remove(sFileToken_nonce)
                self._DEBUG('Successfully deleted "password-nonce" token for user: %s x> %s' % (uUsername, sFileToken_nonce), TokenPlugin.DEBUG_INFO)
            else:
                self._DEBUG('DRY-RUN! NOT deleting "password-nonce" token for user: %s x> %s' % (uUsername, sFileToken_nonce), TokenPlugin.DEBUG_WARNING)
        except Exception as e:
            self._DEBUG('Failed to delete "password-nonce" token; %s' % str(e))
            self._EXIT_ERROR('Internal error; please contact your system administrator')

        # Done
        self._EXIT_OK('Password nonce (PIN code) is no longer valid')

# Process
NukePasswordNonce().process()
