#!/usr/bin/env python3
# -*- mode:python; tab-width:4; c-basic-offset:4; intent-tabs-mode:nil; -*-
# ex: filetype=python tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent

#
# Universal Password Changer (UPwdChg)
# Copyright (C) 2014-2018 Cedric Dufour <http://cedric.dufour.name>
# Author: Cedric Dufour <http://cedric.dufour.name>
#
# The Universal Password Changer (UPwdChg) is free software:
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, Version 3.
#
# The Universal Password Changer (UPwdChg) is distributed in the hope
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#
# SPDX-License-Identifier: GPL-3.0
# License-Filename: LICENSE/GPL-3.0.txt
#

#------------------------------------------------------------------------------
# DEPENDENCIES
#------------------------------------------------------------------------------

# UPwdChg
from UPwdChg import TokenPlugin


#------------------------------------------------------------------------------
# CONFIGURATION
#------------------------------------------------------------------------------

# UPwdChg
UPWDCHG_PLUGIN_NAME='ShowTokenInfo'


#------------------------------------------------------------------------------
# PLUGIN
#------------------------------------------------------------------------------

class ShowTokenInfo(TokenPlugin):

    def __init__(self):
        TokenPlugin.__init__(self, UPWDCHG_PLUGIN_NAME)


    def process(self):
        # Get token (data)
        oToken = self._getToken()

        # Done
        self._EXIT_OK('Got a "%s" token for user %s (created at %s)' % (oToken['type'], oToken['username'], oToken['timestamp']))


# Process
ShowTokenInfo().process()
