#!/usr/bin/env python
# -*- mode:python; tab-width:4; c-basic-offset:4; intent-tabs-mode:nil; -*-
# ex: filetype=python tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent

#
# Universal Password Changer (UPwdChg)
# Copyright (C) 2014 Cedric Dufour <http://cedric.dufour.name>
# Author: Cedric Dufour <http://cedric.dufour.name>
#
# The Universal Password Changer (UPwdChg) is free software:
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, Version 3.
#
# The Universal Password Changer (UPwdChg) is distributed in the hope
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#

# Modules
from UPwdChg import TokenPlugin

# Plugin
class ShowTokenInfo(TokenPlugin):

    def __init__(self):
        global UPWDCHG_PLUGIN_INFO_CRITICAL
        TokenPlugin.__init__(self, 'ShowTokenInfo')

    def process(self):
        # Get token (data)
        oToken = self._getToken()

        # Done
        self._EXIT_OK('Got a "%s" token for user %s (created at %s)' % (oToken['type'], oToken['username'], oToken['timestamp']))

# Process
ShowTokenInfo().process()
