#!/usr/bin/env python
# -*- mode:python; tab-width:4; c-basic-offset:4; intent-tabs-mode:nil; coding:utf-8 -*-
# ex: filetype=python tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent

#
# Universal Password Changer (UPwdChg)
# Copyright (C) 2014 Cedric Dufour <http://cedric.dufour.name>
# Author: Cedric Dufour <http://cedric.dufour.name>
#
# The Universal Password Changer (UPwdChg) is free software:
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, Version 3.
#
# The Universal Password Changer (UPwdChg) is distributed in the hope
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#

# Modules
# ... deb: python-ldap
from UPwdChg import TokenPlugin
import ldap

# Parameters
UPWDCHG_PLUGIN_CRITICAL=True
UPWDCHG_PLUGIN_DRYRUN=True
UPWDCHG_PLUGIN_DEBUG=TokenPlugin.DEBUG_INFO

# ... (source) LDAP directory
UPWDCHG_PLUGIN_LDAP_SRC_URI='ldap://ldap.example.org:389'
UPWDCHG_PLUGIN_LDAP_SRC_ADMIN_DN='cn=admin,dc=example,dc=org'
UPWDCHG_PLUGIN_LDAP_SRC_ADMIN_PWD=''  # prefix with 'file://' to get password from specified file
# ... group synchronization
UPWDCHG_PLUGIN_LDAP_SRC_USER_DN='uid=%{USERNAME},ou=users,dc=example,dc=org'
UPWDCHG_PLUGIN_LDAP_SRC_GROUP_SEARCH_DN='ou=groups,dc=example,dc=org'
UPWDCHG_PLUGIN_LDAP_SRC_GROUP_SEARCH_SCOPE=ldap.SCOPE_ONELEVEL
UPWDCHG_PLUGIN_LDAP_SRC_GROUP_SEARCH_FILTER='(&(objectClass=posixGroup)(memberUid=%{USERNAME}))'
UPWDCHG_PLUGIN_LDAP_SRC_GROUP_ATTR_NAME='cn'

# ... (destination) LDAP directory
UPWDCHG_PLUGIN_LDAP_DST_URI='ldap://ad.example.org:389'
UPWDCHG_PLUGIN_LDAP_DST_ADMIN_DN='Administrator@EXAMPLE.ORG'
UPWDCHG_PLUGIN_LDAP_DST_ADMIN_PWD=''  # prefix with 'file://' to get password from specified file
UPWDCHG_PLUGIN_LDAP_DST_USER_DN=None  # set to None to perform DN search
UPWDCHG_PLUGIN_LDAP_DST_USER_SEARCH_DN='ou=Users,dc=example,dc=org'
UPWDCHG_PLUGIN_LDAP_DST_USER_SEARCH_SCOPE=ldap.SCOPE_ONELEVEL
UPWDCHG_PLUGIN_LDAP_DST_USER_SEARCH_FILTER='(&(objectClass=user)(uid=%{USERNAME}))'
# ... group synchronization
UPWDCHG_PLUGIN_LDAP_DST_GROUP_SEARCH_DN='ou=Users,dc=example,dc=org'
UPWDCHG_PLUGIN_LDAP_DST_GROUP_SEARCH_SCOPE=ldap.SCOPE_ONELEVEL
UPWDCHG_PLUGIN_LDAP_DST_GROUP_SEARCH_FILTER='(&(objectClass=group)(cn=%{GROUPNAME}))'
UPWDCHG_PLUGIN_LDAP_DST_GROUP_ATTR_MEMBER='member'
UPWDCHG_PLUGIN_LDAP_DST_GROUP_ATTR_MEMBER_VALUE='%{USERDN}'
UPWDCHG_PLUGIN_LDAP_DST_GROUP_CRITICAL=False

# Plugin
class SynchGroupsMemberLdap(TokenPlugin):

    def __init__( self ):
        global UPWDCHG_PLUGIN_CRITICAL
        TokenPlugin.__init__( self, 'SynchGroupsMemberLdap', UPWDCHG_PLUGIN_CRITICAL, UPWDCHG_PLUGIN_DEBUG )


    def __ldapSrcBind( self ):
        global \
            UPWDCHG_PLUGIN_LDAP_SRC_URI, \
            UPWDCHG_PLUGIN_LDAP_SRC_ADMIN_DN, \
            UPWDCHG_PLUGIN_LDAP_SRC_ADMIN_PWD

        # Check parameters
        if not UPWDCHG_PLUGIN_LDAP_SRC_URI:
            self._DEBUG( 'Missing (source LDAP) server address (URI)' )
            self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
        if not UPWDCHG_PLUGIN_LDAP_SRC_ADMIN_DN:
            self._DEBUG( 'Missing (source LDAP) administrator distinguished name (DN)' )
            self._EXIT_ERROR( 'Internal error; please contact your system administrator' )

        # Bind to server

        # ... bind credentials
        sBindDn = UPWDCHG_PLUGIN_LDAP_SRC_ADMIN_DN
        if not UPWDCHG_PLUGIN_LDAP_SRC_ADMIN_PWD:
            sBindPwd=''  # Really!?!
        elif UPWDCHG_PLUGIN_LDAP_SRC_ADMIN_PWD.startswith( 'file://' ):
            __sFile = UPWDCHG_PLUGIN_LDAP_SRC_ADMIN_PWD[7:]
            try:
                __oFile = open( __sFile, 'r' )
                sBindPwd = __oFile.readline()
                __oFile.close()
            except Exception as e:
                self._DEBUG( 'Failed to retrieve (source LDAP) bind password from file; %s' % str( e ) )
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
        else:
            sBindPwd = UPWDCHG_PLUGIN_LDAP_SRC_ADMIN_PWD
        self._DEBUG( 'Binding to server as (DN): %s' % sBindDn, TokenPlugin.DEBUG_TRACE )

        # ... bind
        try:
            oLdap = ldap.initialize( UPWDCHG_PLUGIN_LDAP_SRC_URI )
            oLdap.protocol_version = ldap.VERSION3
            oLdap.bind_s( sBindDn, sBindPwd, ldap.AUTH_SIMPLE )
        except Exception as e:
            self._DEBUG( 'Failed to bind to (source LDAP) server; %s' % str( e ) )
            self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
        self._DEBUG( 'Successfully bound to (source LDAP) server', TokenPlugin.DEBUG_NOTICE )

        # Done
        return oLdap


    def __ldapSrcGetGroups( self, oLdap, sUsername ):
        global \
            UPWDCHG_PLUGIN_LDAP_SRC_USER_DN, \
            UPWDCHG_PLUGIN_LDAP_SRC_GROUP_SEARCH_DN, \
            UPWDCHG_PLUGIN_LDAP_SRC_GROUP_SEARCH_SCOPE, \
            UPWDCHG_PLUGIN_LDAP_SRC_GROUP_SEARCH_FILTER, \
            UPWDCHG_PLUGIN_LDAP_SRC_GROUP_ATTR_NAME

        # Return variable
        lGroups = list()

        # Check parameters
        if not UPWDCHG_PLUGIN_LDAP_SRC_GROUP_SEARCH_DN:
            self._DEBUG( 'Missing (source LDAP) group search base (DN)' )
            self._EXIT_ERROR( 'Internal error; please contact your system administrator' )

        # Retrieve user groups

        # ... groups
        try:
            sUserDn = UPWDCHG_PLUGIN_LDAP_SRC_USER_DN.replace( '%{USERNAME}', sUsername )
            lLdapResults = oLdap.search_ext_s(
                UPWDCHG_PLUGIN_LDAP_SRC_GROUP_SEARCH_DN,
                UPWDCHG_PLUGIN_LDAP_SRC_GROUP_SEARCH_SCOPE,
                UPWDCHG_PLUGIN_LDAP_SRC_GROUP_SEARCH_FILTER.replace( '%{USERNAME}', sUsername ).replace( '%{USERDN}', sUserDn ),
                attrlist=[UPWDCHG_PLUGIN_LDAP_SRC_GROUP_ATTR_NAME], attrsonly=0
                )
            for tLdapResult in lLdapResults:
                lGroups.append( ( tLdapResult[1][UPWDCHG_PLUGIN_LDAP_SRC_GROUP_ATTR_NAME][0], tLdapResult[0] ) )
        except Exception as e:
            self._DEBUG( 'Failed to perform (source LDAP) group search; %s' % str( e ) )
            self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
        self._DEBUG( 'Successfully retrieved user groups from (source LDAP) server:\n%s' % str( lGroups ), TokenPlugin.DEBUG_TRACE )

        # Done
        return lGroups


    def __ldapSrcUnbind( self, oLdap ):

        # Unbind
        try:
            oLdap.unbind_s()
        except Exception as e:
            self._DEBUG( 'Failed to unbind from (source LDAP) server; %s' % str( e ) )


    def __ldapDstBind( self ):
        global \
            UPWDCHG_PLUGIN_LDAP_DST_URI, \
            UPWDCHG_PLUGIN_LDAP_DST_ADMIN_DN, \
            UPWDCHG_PLUGIN_LDAP_DST_ADMIN_PWD

        # Check parameters
        if not UPWDCHG_PLUGIN_LDAP_DST_URI:
            self._DEBUG( 'Missing (destination LDAP) server address (URI)' )
            self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
        if not UPWDCHG_PLUGIN_LDAP_DST_ADMIN_DN:
            self._DEBUG( 'Missing (destination LDAP) administrator distinguished name (DN)' )
            self._EXIT_ERROR( 'Internal error; please contact your system administrator' )

        # Bind to server

        # ... bind credentials
        sBindDn = UPWDCHG_PLUGIN_LDAP_DST_ADMIN_DN
        if not UPWDCHG_PLUGIN_LDAP_DST_ADMIN_PWD:
            sBindPwd=''  # Really!?!
        elif UPWDCHG_PLUGIN_LDAP_DST_ADMIN_PWD.startswith( 'file://' ):
            __sFile = UPWDCHG_PLUGIN_LDAP_DST_ADMIN_PWD[7:]
            try:
                __oFile = open( __sFile, 'r' )
                sBindPwd = __oFile.readline()
                __oFile.close()
            except Exception as e:
                self._DEBUG( 'Failed to retrieve (destination LDAP) bind password from file; %s' % str( e ) )
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
        else:
            sBindPwd = UPWDCHG_PLUGIN_LDAP_DST_ADMIN_PWD
        self._DEBUG( 'Binding to (destination LDAP) server as (DN): %s' % sBindDn, TokenPlugin.DEBUG_TRACE )

        # ... bind
        try:
            oLdap = ldap.initialize( UPWDCHG_PLUGIN_LDAP_DST_URI )
            oLdap.protocol_version = ldap.VERSION3
            oLdap.bind_s( sBindDn, sBindPwd, ldap.AUTH_SIMPLE )
        except Exception as e:
            self._DEBUG( 'Failed to bind to (destination LDAP) server; %s' % str( e ) )
            self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
        self._DEBUG( 'Successfully bound to (destination LDAP) server', TokenPlugin.DEBUG_NOTICE )

        # Done
        return oLdap


    def __ldapDstGetUserDn( self, oLdap, sUsername ):
        global \
            UPWDCHG_PLUGIN_LDAP_DST_USER_DN, \
            UPWDCHG_PLUGIN_LDAP_DST_USER_SEARCH_DN, \
            UPWDCHG_PLUGIN_LDAP_DST_USER_SEARCH_SCOPE, \
            UPWDCHG_PLUGIN_LDAP_DST_USER_SEARCH_FILTER

        # Retrieve user DN
        if not UPWDCHG_PLUGIN_LDAP_DST_USER_DN:
            try:
                lLdapResults = oLdap.search_ext_s(
                    UPWDCHG_PLUGIN_LDAP_DST_USER_SEARCH_DN,
                    UPWDCHG_PLUGIN_LDAP_DST_USER_SEARCH_SCOPE,
                    UPWDCHG_PLUGIN_LDAP_DST_USER_SEARCH_FILTER.replace( '%{USERNAME}', sUsername ),
                    attrlist=None, attrsonly=1, sizelimit=2
                    )
                if not lLdapResults:
                    raise Exception( 'user not found' )
                elif len( lLdapResults ) > 1:
                    raise Exception( 'too many match' )
            except Exception as e:
                self._DEBUG( 'Failed to perform (destination LDAP) user search; %s' % str( e ) )
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
        else:
            try:
                lLdapResults = oLdap.search_ext_s(
                    UPWDCHG_PLUGIN_LDAP_DST_USER_DN.replace( '%{USERNAME}', sUsername ),
                    ldap.SCOPE_BASE,
                    '(objectClass=*)',
                    attrlist=None, attrsonly=1, sizelimit=2
                    )
                if not lLdapResults:
                    raise Exception( 'user not found' )
                elif len( lLdapResults ) > 1:
                    raise Exception( 'too many match' )
            except Exception as e:
                self._DEBUG( 'Failed to perform (destination LDAP) user search; %s' % str( e ) )
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
        sUserDn = lLdapResults[0][0]
        self._DEBUG( 'Successfully got (destination LDAP) user distinguished name (DN): %s' % sUserDn, TokenPlugin.DEBUG_TRACE )

        # Done
        return sUserDn


    def __ldapDstAddUserToGroup( self, oLdap, sUsername, sUserDn, sGroupname ):
        global \
            UPWDCHG_PLUGIN_DRYRUN, \
            UPWDCHG_PLUGIN_LDAP_DST_GROUP_SEARCH_DN, \
            UPWDCHG_PLUGIN_LDAP_DST_GROUP_SEARCH_SCOPE, \
            UPWDCHG_PLUGIN_LDAP_DST_GROUP_SEARCH_FILTER, \
            UPWDCHG_PLUGIN_LDAP_DST_GROUP_ATTR_MEMBER, \
            UPWDCHG_PLUGIN_LDAP_DST_GROUP_ATTR_MEMBER_VALUE, \
            UPWDCHG_PLUGIN_LDAP_DST_GROUP_CRITICAL

        # Add user to group

        # ... group DN
        try:
            lLdapResults = oLdap.search_ext_s(
                UPWDCHG_PLUGIN_LDAP_DST_GROUP_SEARCH_DN,
                UPWDCHG_PLUGIN_LDAP_DST_GROUP_SEARCH_SCOPE,
                UPWDCHG_PLUGIN_LDAP_DST_GROUP_SEARCH_FILTER.replace( '%{GROUPNAME}', sGroupname ),
                attrlist=None, attrsonly=1, sizelimit=2
                )
            if not lLdapResults:
                raise Exception( 'group not found' )
            elif len( lLdapResults ) > 1:
                raise Exception( 'too many match' )
        except Exception as e:
            self._DEBUG( 'Failed to perform (destination LDAP) group search; %s' % str( e ) )
            if UPWDCHG_PLUGIN_LDAP_DST_GROUP_CRITICAL:
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
            else:
                return
        sGroupDn = lLdapResults[0][0]

        # ... check group membership
        sMembershipAttr = UPWDCHG_PLUGIN_LDAP_DST_GROUP_ATTR_MEMBER
        sMembershipAttrValue = UPWDCHG_PLUGIN_LDAP_DST_GROUP_ATTR_MEMBER_VALUE.replace( '%{USERNAME}', sUsername ).replace( '%{USERDN}', sUserDn )
        try:
            lLdapResults = oLdap.search_ext_s(
                sGroupDn,
                ldap.SCOPE_BASE,
                '(%s=%s)' % ( sMembershipAttr, sMembershipAttrValue ),
                attrlist=None, attrsonly=1, sizelimit=2
                )
            if not lLdapResults:
                pass
            elif len( lLdapResults ) > 1:
                raise Exception( 'too many match' )
            else:
                self._DEBUG( 'Group membership already exists in (destination LDAP) server: %s' % lLdapResults[0][0], TokenPlugin.DEBUG_NOTICE )
                return
        except Exception as e:
            self._DEBUG( 'Failed to check (destination LDAP) group membership; %s' % str( e ) )
            if UPWDCHG_PLUGIN_LDAP_DST_GROUP_CRITICAL:
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )

        # ... add group membership
        if UPWDCHG_PLUGIN_DRYRUN:
            return
        try:
            lLDIF = [ ( ldap.MOD_ADD, sMembershipAttr, sMembershipAttrValue ) ]
            oLdap.modify_s( sGroupDn, lLDIF )
        except Exception as e:
            self._DEBUG( 'Failed to add (destination LDAP) group membership; %s' % str( e ) )
            if UPWDCHG_PLUGIN_LDAP_DST_GROUP_CRITICAL:
                self._EXIT_ERROR( 'Internal error; please contact your system administrator' )
            else:
                return
        self._DEBUG( 'Successfully added (destination LDAP) group membership (DN): %s' % sGroupDn, TokenPlugin.DEBUG_INFO )


    def __ldapDstUnbind( self, oLdap ):

        # Unbind
        try:
            oLdap.unbind_s()
        except Exception as e:
            self._DEBUG( 'Failed to unbind from (destination LDAP) server; %s' % str( e ) )


    def process( self ):

        # Get token (data)
        dToken = self._getToken()
        sUsername = dToken['username'].encode( 'utf-8' )
        sPasswordOld = dToken['password-old'].encode( 'utf-8' )

        # Process token data
        bUserExists = True

        # ... (destination LDAP) bind
        oLdapDst = self.__ldapDstBind()

        # ... (destination LDAP) user DN
        sUserDn = self.__ldapDstGetUserDn( oLdapDst, sUsername )

        # ... groups membership synchronization
        oLdapSrc = self.__ldapSrcBind()
        lGroups = self.__ldapSrcGetGroups( oLdapSrc, sUsername )
        for tGroup in lGroups:
            self.__ldapDstAddUserToGroup( oLdapDst, sUsername, sUserDn, tGroup[0] )
        self.__ldapSrcUnbind( oLdapSrc )

        # ... (destination LDAP) unbind
        self.__ldapDstUnbind( oLdapDst )

        # Done
        self._EXIT_OK( 'Groups membership successfully synchronized' )

# Process
SynchGroupsMemberLdap().process()
